baseURL = "https://ibby-hugo-tutorial.github.io"
languageCode = "en-us"
title = "The Coolest Blog"
theme="anubis"

[menu]

[[menu.main]]
name = "Photography"
url = "/categories/photography"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2